//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVista01.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudad", Namespace="http://schemas.datacontract.org/2004/07/WCF_Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class Ciudad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomCiudadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                if ((this.idCiudadField.Equals(value) != true)) {
                    this.idCiudadField = value;
                    this.RaisePropertyChanged("idCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomCiudad {
            get {
                return this.nomCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.nomCiudadField, value) != true)) {
                    this.nomCiudadField = value;
                    this.RaisePropertyChanged("nomCiudad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Horario", Namespace="http://schemas.datacontract.org/2004/07/WCF_Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class Horario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechasalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horasalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idHorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string placaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechasalida {
            get {
                return this.fechasalidaField;
            }
            set {
                if ((this.fechasalidaField.Equals(value) != true)) {
                    this.fechasalidaField = value;
                    this.RaisePropertyChanged("fechasalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string horasalida {
            get {
                return this.horasalidaField;
            }
            set {
                if ((object.ReferenceEquals(this.horasalidaField, value) != true)) {
                    this.horasalidaField = value;
                    this.RaisePropertyChanged("horasalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                if ((this.idCiudadField.Equals(value) != true)) {
                    this.idCiudadField = value;
                    this.RaisePropertyChanged("idCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idHorario {
            get {
                return this.idHorarioField;
            }
            set {
                if ((this.idHorarioField.Equals(value) != true)) {
                    this.idHorarioField = value;
                    this.RaisePropertyChanged("idHorario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                if ((object.ReferenceEquals(this.placaField, value) != true)) {
                    this.placaField = value;
                    this.RaisePropertyChanged("placa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pasaje", Namespace="http://schemas.datacontract.org/2004/07/WCF_Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class Pasaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idHorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nasientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int npasajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dniper {
            get {
                return this.dniperField;
            }
            set {
                if ((object.ReferenceEquals(this.dniperField, value) != true)) {
                    this.dniperField = value;
                    this.RaisePropertyChanged("dniper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idHorario {
            get {
                return this.idHorarioField;
            }
            set {
                if ((this.idHorarioField.Equals(value) != true)) {
                    this.idHorarioField = value;
                    this.RaisePropertyChanged("idHorario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nasiento {
            get {
                return this.nasientoField;
            }
            set {
                if ((this.nasientoField.Equals(value) != true)) {
                    this.nasientoField = value;
                    this.RaisePropertyChanged("nasiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomper {
            get {
                return this.nomperField;
            }
            set {
                if ((object.ReferenceEquals(this.nomperField, value) != true)) {
                    this.nomperField = value;
                    this.RaisePropertyChanged("nomper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int npasaje {
            get {
                return this.npasajeField;
            }
            set {
                if ((this.npasajeField.Equals(value) != true)) {
                    this.npasajeField = value;
                    this.RaisePropertyChanged("npasaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listadoCiudad", ReplyAction="http://tempuri.org/IService1/listadoCiudadResponse")]
        WebVista01.ServiceReference2.Ciudad[] listadoCiudad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listadoCiudad", ReplyAction="http://tempuri.org/IService1/listadoCiudadResponse")]
        System.Threading.Tasks.Task<WebVista01.ServiceReference2.Ciudad[]> listadoCiudadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listado_Horarios", ReplyAction="http://tempuri.org/IService1/listado_HorariosResponse")]
        WebVista01.ServiceReference2.Horario[] listado_Horarios(int idCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listado_Horarios", ReplyAction="http://tempuri.org/IService1/listado_HorariosResponse")]
        System.Threading.Tasks.Task<WebVista01.ServiceReference2.Horario[]> listado_HorariosAsync(int idCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/horario_Esp", ReplyAction="http://tempuri.org/IService1/horario_EspResponse")]
        WebVista01.ServiceReference2.Horario horario_Esp(int idHorario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/horario_Esp", ReplyAction="http://tempuri.org/IService1/horario_EspResponse")]
        System.Threading.Tasks.Task<WebVista01.ServiceReference2.Horario> horario_EspAsync(int idHorario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listado_Pasajes", ReplyAction="http://tempuri.org/IService1/listado_PasajesResponse")]
        WebVista01.ServiceReference2.Pasaje[] listado_Pasajes(int idHorario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listado_Pasajes", ReplyAction="http://tempuri.org/IService1/listado_PasajesResponse")]
        System.Threading.Tasks.Task<WebVista01.ServiceReference2.Pasaje[]> listado_PasajesAsync(int idHorario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_asiento", ReplyAction="http://tempuri.org/IService1/agregar_asientoResponse")]
        string agregar_asiento(WebVista01.ServiceReference2.Pasaje reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_asiento", ReplyAction="http://tempuri.org/IService1/agregar_asientoResponse")]
        System.Threading.Tasks.Task<string> agregar_asientoAsync(WebVista01.ServiceReference2.Pasaje reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Horarios", ReplyAction="http://tempuri.org/IService1/HorariosResponse")]
        WebVista01.ServiceReference2.Horario[] Horarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Horarios", ReplyAction="http://tempuri.org/IService1/HorariosResponse")]
        System.Threading.Tasks.Task<WebVista01.ServiceReference2.Horario[]> HorariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebVista01.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebVista01.ServiceReference2.IService1>, WebVista01.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebVista01.ServiceReference2.Ciudad[] listadoCiudad() {
            return base.Channel.listadoCiudad();
        }
        
        public System.Threading.Tasks.Task<WebVista01.ServiceReference2.Ciudad[]> listadoCiudadAsync() {
            return base.Channel.listadoCiudadAsync();
        }
        
        public WebVista01.ServiceReference2.Horario[] listado_Horarios(int idCiudad) {
            return base.Channel.listado_Horarios(idCiudad);
        }
        
        public System.Threading.Tasks.Task<WebVista01.ServiceReference2.Horario[]> listado_HorariosAsync(int idCiudad) {
            return base.Channel.listado_HorariosAsync(idCiudad);
        }
        
        public WebVista01.ServiceReference2.Horario horario_Esp(int idHorario) {
            return base.Channel.horario_Esp(idHorario);
        }
        
        public System.Threading.Tasks.Task<WebVista01.ServiceReference2.Horario> horario_EspAsync(int idHorario) {
            return base.Channel.horario_EspAsync(idHorario);
        }
        
        public WebVista01.ServiceReference2.Pasaje[] listado_Pasajes(int idHorario) {
            return base.Channel.listado_Pasajes(idHorario);
        }
        
        public System.Threading.Tasks.Task<WebVista01.ServiceReference2.Pasaje[]> listado_PasajesAsync(int idHorario) {
            return base.Channel.listado_PasajesAsync(idHorario);
        }
        
        public string agregar_asiento(WebVista01.ServiceReference2.Pasaje reg) {
            return base.Channel.agregar_asiento(reg);
        }
        
        public System.Threading.Tasks.Task<string> agregar_asientoAsync(WebVista01.ServiceReference2.Pasaje reg) {
            return base.Channel.agregar_asientoAsync(reg);
        }
        
        public WebVista01.ServiceReference2.Horario[] Horarios() {
            return base.Channel.Horarios();
        }
        
        public System.Threading.Tasks.Task<WebVista01.ServiceReference2.Horario[]> HorariosAsync() {
            return base.Channel.HorariosAsync();
        }
    }
}
