//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVista01.ReferenciaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCF_Servicio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idclienteField, value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idpaisField, value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrecia {
            get {
                return this.nombreciaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreciaField, value) != true)) {
                    this.nombreciaField = value;
                    this.RaisePropertyChanged("nombrecia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pais", Namespace="http://schemas.datacontract.org/2004/07/WCF_Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrepaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idpaisField, value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrepais {
            get {
                return this.nombrepaisField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrepaisField, value) != true)) {
                    this.nombrepaisField = value;
                    this.RaisePropertyChanged("nombrepais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listado", ReplyAction="http://tempuri.org/IService1/listadoResponse")]
        WebVista01.ReferenciaServicio.Cliente[] listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listado", ReplyAction="http://tempuri.org/IService1/listadoResponse")]
        System.Threading.Tasks.Task<WebVista01.ReferenciaServicio.Cliente[]> listadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Agregar", ReplyAction="http://tempuri.org/IService1/AgregarResponse")]
        string Agregar(WebVista01.ReferenciaServicio.Cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Agregar", ReplyAction="http://tempuri.org/IService1/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(WebVista01.ReferenciaServicio.Cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Actualizar", ReplyAction="http://tempuri.org/IService1/ActualizarResponse")]
        string Actualizar(WebVista01.ReferenciaServicio.Cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Actualizar", ReplyAction="http://tempuri.org/IService1/ActualizarResponse")]
        System.Threading.Tasks.Task<string> ActualizarAsync(WebVista01.ReferenciaServicio.Cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Buscar", ReplyAction="http://tempuri.org/IService1/BuscarResponse")]
        WebVista01.ReferenciaServicio.Cliente Buscar(string idcli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Buscar", ReplyAction="http://tempuri.org/IService1/BuscarResponse")]
        System.Threading.Tasks.Task<WebVista01.ReferenciaServicio.Cliente> BuscarAsync(string idcli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPaises", ReplyAction="http://tempuri.org/IService1/ListarPaisesResponse")]
        WebVista01.ReferenciaServicio.Pais[] ListarPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPaises", ReplyAction="http://tempuri.org/IService1/ListarPaisesResponse")]
        System.Threading.Tasks.Task<WebVista01.ReferenciaServicio.Pais[]> ListarPaisesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebVista01.ReferenciaServicio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebVista01.ReferenciaServicio.IService1>, WebVista01.ReferenciaServicio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebVista01.ReferenciaServicio.Cliente[] listado() {
            return base.Channel.listado();
        }
        
        public System.Threading.Tasks.Task<WebVista01.ReferenciaServicio.Cliente[]> listadoAsync() {
            return base.Channel.listadoAsync();
        }
        
        public string Agregar(WebVista01.ReferenciaServicio.Cliente reg) {
            return base.Channel.Agregar(reg);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(WebVista01.ReferenciaServicio.Cliente reg) {
            return base.Channel.AgregarAsync(reg);
        }
        
        public string Actualizar(WebVista01.ReferenciaServicio.Cliente reg) {
            return base.Channel.Actualizar(reg);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarAsync(WebVista01.ReferenciaServicio.Cliente reg) {
            return base.Channel.ActualizarAsync(reg);
        }
        
        public WebVista01.ReferenciaServicio.Cliente Buscar(string idcli) {
            return base.Channel.Buscar(idcli);
        }
        
        public System.Threading.Tasks.Task<WebVista01.ReferenciaServicio.Cliente> BuscarAsync(string idcli) {
            return base.Channel.BuscarAsync(idcli);
        }
        
        public WebVista01.ReferenciaServicio.Pais[] ListarPaises() {
            return base.Channel.ListarPaises();
        }
        
        public System.Threading.Tasks.Task<WebVista01.ReferenciaServicio.Pais[]> ListarPaisesAsync() {
            return base.Channel.ListarPaisesAsync();
        }
    }
}
